import Head from "next/head";
import Image from "next/image";
import { Rubik, Rubik_Maze } from "next/font/google";
import Navbarr from "@/components/Navbar";
import { Button } from 'reactstrap';
const inter = Rubik({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
 
      <Head>
        <title>tuto </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main >
      <Navbarr />
        <h1>WELCOME!</h1>
   
      </main>
     
   
    </>
  );
}
